apiVersion: v1
kind: Service
metadata:
  name: backend # The name is up to you
spec:
  selector: # Define which pods should be part of this service
    app: second-app # We can also add the tier:backend label if we want to be more specific
  ports:
    - protocol: "TCP" # Default
      port: 81 # Outside the application
      targetPort: 8080 # Inside the application
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: second-app-deployment
  labels:
    group: example
spec: # Configuration of the overall deployment
  replicas: 1
  selector:
    matchLabels: # All values like this must be controlled with this deployment; otherwise they won't be controlled
      app: second-app # This is matched with your template.metadata.labels.app
      tier: backend # This is matched with your template.metadata.labels.tier
  template: # Define the pods that should be created as part of this deployment
    metadata:
      labels: # The keys and values are up to you
        app: second-app
        tier: backend
    spec: # Specification of the individual pod; you can have more than one container
      containers: # The keys and values are up to you
        - name: second-node
          image: planaterobotics/kub-first-app:2 # Needs to be in docker hub
